@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyEmployeeTracker <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class EmployeeTracker
Class ReadOnlyEmployeeTracker
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Employee {
Class Employee
Class Address
Class DateOfBirth
Class DateOfJoining
Class Email
Class Name
Class Phone
Class Role
Class Salary
Class UniqueEmployeeList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

EmployeeTracker .up.|> ReadOnlyEmployeeTracker

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" EmployeeTracker
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

EmployeeTracker *--> "1" UniqueEmployeeList
UniqueEmployeeList o--> "*" Employee
Employee *--> Address
Employee *--> DateOfBirth
Employee *--> DateOfJoining
Employee *--> Email
Employee *--> Name
Employee *--> Phone
Employee *--> Role
Employee *--> Salary
Employee *--> "*" Tag

ModelManager -----> "                                   ~* filtered list" Employee

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email
Email -[hidden]right-> Role


@enduml
