title: "Addressbook NS Edition (ABNS)"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "https://github.com/AY2021S2-TIC4002-F18-3/tp2"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
