title: "PB-3"
theme: jekyll-theme-merlot

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S2-TIC4002-F18-4/tp2"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
